kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 10
  selector:
    name: locust
    role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: gcr.io/cloud-solutions-images/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              key: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              key: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              key: TARGET_HOST
              value: http://workload-simulation-webapp.appspot.com